CREATE TABLE "user" (
"user_id" SERIAL NOT NULL PRIMARY KEY,
"email" VARCHAR(500) NOT NULL UNIQUE,
"mobile" VARCHAR(13) NOT NULL UNIQUE,
"password" VARCHAR(500) NOT NULL,
"name" VARCHAR(50) NOT NULL DEFAULT 'ABC',
"session" VARCHAR(100)
)