# Generated by Django 3.0.8 on 2020-08-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('password', models.CharField(default='password', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deviceDetail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.UserProfile')),
            ],
        ),
    ]
