# Generated by Django 3.0.8 on 2020-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
