# Generated by Django 3.0.8 on 2020-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('session', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deviceDetail', models.TextField()),
            ],
        ),
    ]
